name: Haskell CD with Stack

on:
  push:
    branches:
      - 'ID-04/Comment'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with: 
          ghc-version: '9.4.8'
          enable-stack: true
          stack-version: '2.13.1'

      - name: Install Dependencies
        run: stack build --only-dependencies

      - name: Build using Stack
        run: stack build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test using Stack
        run: stack test

  check_branches_convention:
    name: Conventional Branches Name
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name convention
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^ID-\d+\/[A-Za-z0-9]+$'
          allowed_prefixes: 'ID'
          ignore: 'main,develop'
          min_length: 4
          max_length: 100
